services:
  # ===================================================================================================================================================================================
  backend:
    command: npm run start:dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
  # ===================================================================================================================================================================================
  frontend:
    command: npm run dev
    # command: /bin/sh -c "npm run build && npm run start"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
  # ===================================================================================================================================================================================
  caddy:
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
  # ===================================================================================================================================================================================
  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOST=${APP_REDIS_HOST}
      - REDIS_PORT=${APP_REDIS_PORT}
      - REDIS_PASSWORD=GhostLexly.7
    ports:
      - "8081:8081"
