services:
  # ===================================================================================================================================================================================
  backend:
    image: fenrisshq/terracapital:backend
    build:
      context: ./backend
    environment:
      - NODE_ENV=production
      - FORCE_COLOR=1
      - DISPLAY=${X11_DISPLAY}
      - APP_PORT=${APP_PORT}
      - APP_BASE_URL=${APP_BASE_URL}
      - APP_DATABASE_CONNECTION_URL=${APP_DATABASE_CONNECTION_URL}
      - APP_REDIS_HOST=${APP_REDIS_HOST}
      - APP_REDIS_PORT=${APP_REDIS_PORT}
      - APP_JWT_PRIVATE_KEY=${APP_JWT_PRIVATE_KEY}
      - APP_JWT_PUBLIC_KEY=${APP_JWT_PUBLIC_KEY}
      - API_S3_ENDPOINT=${API_S3_ENDPOINT}
      - API_S3_ACCESS_KEY=${API_S3_ACCESS_KEY}
      - API_S3_SECRET_KEY=${API_S3_SECRET_KEY}
      - API_S3_BUCKET=${API_S3_BUCKET}
      - API_GOOGLE_CLIENT_ID=${API_GOOGLE_CLIENT_ID}
      - API_GOOGLE_CLIENT_SECRET=${API_GOOGLE_CLIENT_SECRET}
      - APP_PLAYWRIGHT_HEADLESS=${APP_PLAYWRIGHT_HEADLESS}
      - SENTRY_AUTH_TOKEN=${API_SENTRY_AUTH_TOKEN}
    volumes:
      - ./backend/logs:/usr/src/app/logs
    depends_on:
      - redis
    tty: true
    restart: unless-stopped
  # ===================================================================================================================================================================================
  frontend:
    image: fenrisshq/terracapital:frontend
    build:
      context: ./frontend
    environment:
      - NODE_ENV=production
    restart: unless-stopped
  # ===================================================================================================================================================================================
  caddy:
    image: fenrisshq/terracapital:caddy
    build:
      context: ./caddy
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - ./caddy/logs:/var/log/caddy:z
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
  # ===================================================================================================================================================================================
  redis:
    image: bitnami/redis:7.0.8
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory-policy noeviction
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami/redis/data
    restart: unless-stopped
  # ===================================================================================================================================================================================
  postgres:
    image: postgres:17.2
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_USER=lunisoft
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${PROJECT_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  caddy_data:
  caddy_config:
