import type { Metadata } from "next";
import "@/assets/styles/globals.css";
import { Footer } from "./footer";
import { Header } from "./header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const DefaultLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Header />

      {children}

      <Footer />
    </>
  );
};

export default DefaultLayout;
